bilans_dict = {
    'Aktywa': 'Aktywa',
    'Aktywa_A': '● Aktywa trwałe', 
    'Aktywa_A_I': '●● Wartości niematerialne i prawne',
    'Aktywa_A_I_1': '●●● Koszty zakończonych prac rozwojowych',
    'Aktywa_A_I_2': '●●● Wartość firmy',
    'Aktywa_A_I_3': '●●● Inne wartości niematerialne i prawne',
    'Aktywa_A_I_4': '●●● Zaliczki na wartości niematerialne i prawne',
    'Aktywa_A_II' : ' ●● Rzeczowe aktywa trwałe',
    'Aktywa_A_II_1': ' ●●● Środki trwałe',
    'Aktywa_A_II_1_A': '●●●● Grunty (w tym prawo użytkowania wieczystego gruntu)',
    'Aktywa_A_II_1_B': '●●●● Budynki, lokale, prawa do lokali i obiekty inżynierii lądowej i wodnej',
    'Aktywa_A_II_1_C': '●●●● Urządzenia techniczne i maszyny',
    'Aktywa_A_II_1_D': '●●●● Środki transportu',
    'Aktywa_A_II_1_E': '●●●● Inne środki trwałe',
    'Aktywa_A_II_2': '●●● Środki trwałe w budowie',
    'Aktywa_A_II_3': '●●● Zaliczki na środki trwałe w budowie',
    'Aktywa_A_III': '●● Należności długoterminowe',
    'Aktywa_A_III_1': '●●● Od jednostek powiązanych',
    'Aktywa_A_III_2': '●●● Od pozostałych jednostek, w których jednostka posiada zaangażowanie w kapitale',
    'Aktywa_A_III_3': '●●● Od pozostałych jednostek',
    'Aktywa_A_IV': '●● Inwestycje długoterminowe',
    'Aktywa_A_IV_1': '●●● Nieruchomości',
    'Aktywa_A_IV_2': '●●● Wartości niematerialne i prawne',
    'Aktywa_A_IV_3': '●●● Długoterminowe aktywa finansowe',
    'Aktywa_A_IV_3_A': '●●●● W jednostkach powiązanych',
    'Aktywa_A_IV_3_A_1': '●●●●● Udziały lub akcje',
    'Aktywa_A_IV_3_A_2': '●●●●● Inne papiery wartościowe',
    'Aktywa_A_IV_3_A_3': '●●●●● Udzielone pożyczki',
    'Aktywa_A_IV_3_A_4': '●●●●● Inne długoterminowe aktywa finansowe',
    'Aktywa_A_IV_3_B': ' ●●●● W pozostałych jednostkach, w których jednostka posiada zaangażowanie w kapitale',
    'Aktywa_A_IV_3_B_1': '●●●●● Udziały lub akcje',
    'Aktywa_A_IV_3_B_2': '●●●●● Inne papiery wartościowe',
    'Aktywa_A_IV_3_B_3': '●●●●● Udzielone pożyczki',
    'Aktywa_A_IV_3_B_4': '●●●●● Inne długoterminowe aktywa finansowe',
    'Aktywa_A_IV_3_C': '●●●● W pozostałych jednostkach',
    'Aktywa_A_IV_3_C_1': '●●●●● Udziały lub akcje',
    'Aktywa_A_IV_3_C_2': '●●●●● Inne papiery wartościowe',
    'Aktywa_A_IV_3_C_3': '●●●●● Udzielone pożyczki',
    'Aktywa_A_IV_3_C_4': '●●●●● Inne długoterminowe aktywa finansowe',
    'Aktywa_A_IV_4': '●●● Inne inwestycje długoterminowe',
    'Aktywa_A_V': '●● Długoterminowe rozliczenia międzyokresowe', 
    'Aktywa_A_V_1' : '●●● Aktywa z tytułu odroczonego podatku dochodowego',
    'Aktywa_A_V_2' : '●●● Inne rozliczenia międzyokresowe',
    'Aktywa_B': '● Aktywa obrotowe',
    'Aktywa_B_I': '●● Zapasy',
    'Aktywa_B_I_1': '●●● Materiały',
    'Aktywa_B_I_2': '●●● Półprodukty i produkty w toku', 
    'Aktywa_B_I_3': '●●● Produkty gotowe',
    'Aktywa_B_I_4': '●●● Towary',
    'Aktywa_B_I_5': '●●● Zaliczki na dostawy i usługi',
    'Aktywa_B_II': '●● Należności krótkoterminowe',
    'Aktywa_B_II_1': '●●● Należności od jednostek powiązanych',
    'Aktywa_B_II_1_A': '●●●● Z tytułu dostaw i usług, o okresie spłaty:',
    'Aktywa_B_II_1_A_1': '●●●●● Do 12 miesięcy',
    'Aktywa_B_II_1_A_2': '●●●●● Powyżej 12 miesięcy',
    'Aktywa_B_II_1_B': '●●●● Inne',
    'Aktywa_B_II_2': '●●● Należności od pozostałych jednostek, w których jednostka posiada zaangażowanie w kapitale',
    'Aktywa_B_II_2_A': '●●●● Z tytułu dostaw i usług, o okresie spłaty:',
    'Aktywa_B_II_2_A_1': '●●●●● Do 12 miesięcy',
    'Aktywa_B_II_2_A_2': '●●●●● Powyżej 12 miesięcy',
    'Aktywa_B_II_2_B': '●●●● Inne',
    'Aktywa_B_II_3': '●●● Należności od pozostałych jednostek',
    'Aktywa_B_II_3_A': '●●●● Z tytułu dostaw i usług, o okresie spłaty:',
    'Aktywa_B_II_3_A_1': '●●●●● Do 12 miesięcy',
    'Aktywa_B_II_3_A_2': '●●●●● Powyżej 12 miesięcy',
    'Aktywa_B_II_3_B': '●●●● z tytułu podatków, dotacji, ceł, ubezpieczeń społecznych i zdrowotnych oraz innych tytułów publicznoprawnych',
    'Aktywa_B_II_3_C': '●●●● Inne',
    'Aktywa_B_II_3_D': '●●●● Dochodzone na drodze sądowej',
    'Aktywa_B_III': '●● Inwestycje krótkoterminowe',
    'Aktywa_B_III_1': '●●● Krótkoterminowe aktywa finansowe',
    'Aktywa_B_III_1_A': '●●●● W jednostkach powiązanych',
    'Aktywa_B_III_1_A_1': '●●●●● Udziały lub akcje',
    'Aktywa_B_III_1_A_2': '●●●●● Inne papiery wartościowe',
    'Aktywa_B_III_1_A_4': '●●●●● Udzielone pożyczki',
    'Aktywa_B_III_1_B': '●●●● W pozostałych jednostkach',
    'Aktywa_B_III_1_B_1': '●●●●● Udziały lub akcje',
    'Aktywa_B_III_1_B_2': '●●●●● Inne papiery wartościowe',
    'Aktywa_B_III_1_B_3': '●●●●● Udzielone pożyczki',
    'Aktywa_B_III_1_B_4': '●●●●● Inne krótkoterminowe aktywa finansowe',
    'Aktywa_B_III_1_C': '●●●● Środki pieniężne i inne aktywa pieniężne',
    'Aktywa_B_III_1_C_1': '●●●●● Środki pieniężne w kasie i na rachunkach',
    'Aktywa_B_III_1_C_2': '●●●●● Inne środki pieniężne',
    'Aktywa_B_III_1_C_3': '●●●●● Inne aktywa pieniężne',
    'Aktywa_B_III_2': '●●● Inne inwestycje krótkoterminowe',
    'Aktywa_B_IV': '●● Krótkoterminowe rozliczenia międzyokresowe',
    'Aktywa_C': '● Należne wpłaty na kapitał (fundusz) podstawowy',
    'Aktywa_D': '● Udziały (akcje) własne',
    'Pasywa': 'Pasywa',
    'Pasywa_A': '● Kapitał (fundusz) własny',
    'Pasywa_A_I': '●● Kapitał (fundusz) podstawowy',
    'Pasywa_A_II': '●● Kapitał (fundusz) zapasowy, w tym:',
    'Pasywa_A_II_1': '●●● Nadwyżka wartości sprzedaży (wartości emisyjnej) nad wartością nominalną udziałów (akcji)',
    'Pasywa_A_III': '●● Kapitał (fundusz) z aktualizacji wyceny, w tym:',
    'Pasywa_A_III_1': '●●● Z tytułu aktualizacji wartości godziwej',
    'Pasywa_A_IV': '●● Pozostałe kapitały (fundusze) rezerwowe, w tym:',
    'Pasywa_A_IV_1': '●●● Tworzone zgodnie z umową (statutem) spółki',
    'Pasywa_A_IV_2': '●●● Na udziały (akcje) własne',
    'Pasywa_A_V': '●● Zysk (strata) z lat ubiegłych',
    'Pasywa_A_VI': '●● Zysk (strata) netto',
    'Pasywa_A_VII': '●● Odpisy z zysku netto w ciągu roku obrotowego (wielkość ujemna)',
    'Pasywa_B': '● Zobowiązania i rezerwy na zobowiązania',
    'Pasywa_B_I': '●● Rezerwy na zobowiązania',
    'Pasywa_B_I_1': '●●● Rezerwa z tytułu odroczonego podatku dochodowego',
    'Pasywa_B_I_2': '●●● Rezerwa na świadczenia emerytalne i podobne',
    'Pasywa_B_I_2_1': '●●●● Długoterminowa',
    'Pasywa_B_I_2_2': '●●●● Krótkoterminowa',
    'Pasywa_B_I_3': '●●● Pozostałe rezerwy',
    'Pasywa_B_I_3_1': '●●●● Długoterminowe',
    'Pasywa_B_I_3_2': '●●●● Krótkoterminowe',
    'Pasywa_B_II': '●● Zobowiązania długoterminowe',
    'Pasywa_B_II_1': '●●● Wobec jednostek powiązanych',
    'Pasywa_B_II_2': '●●● Wobec pozostałych jednostek, w których jednostka posiada zaangażowanie w kapitale',
    'Pasywa_B_II_3': '●●● Wobec pozostałych jednostek',
    'Pasywa_B_II_3_A': '●●●● Kredyty i pożyczki',
    'Pasywa_B_II_3_B': '●●●● Z tytułu emisji dłużnych papierów wartościowych',
    'Pasywa_B_II_3_C': '●●●● Inne zobowiązania finansowe',
    'Pasywa_B_II_3_D': '●●●● Zobowiązania wekslowe',
    'Pasywa_B_II_3_E': '●●●● Inne',
    'Pasywa_B_III': '●● Zobowiązania krótkoterminowe',
    'Pasywa_B_III_1': '●●● Zobowiązania wobec jednostek powiązanych',
    'Pasywa_B_III_1_A': '●●●● Z tytułu dostaw i usług, o okresie wymagalności',
    'Pasywa_B_III_1_A_1': '●●●●● Do 12 miesięcy',
    'Pasywa_B_III_1_A_2': '●●●●● Powyżej 12 miesięcy',
    'Pasywa_B_III_1_B': '●●●● Inne',
    'Pasywa_B_III_2': '●●● Zobowiązania wobec pozostałych jednostek, w których jednostka posiada zaangażowanie w kapitale',
    'Pasywa_B_III_2_A': '●●●● Z tytułu dostaw i usług, o okresie wymagalności',
    'Pasywa_B_III_2_A_1': '●●●●● Do 12 miesięcy',
    'Pasywa_B_III_2_A_2': '●●●●● Powyżej 12 miesięcy',
    'Pasywa_B_III_2_B': '●●●● Inne',
    'Pasywa_B_III_3': '●●● Zobowiązania wobec pozostałych jednostek',
    'Pasywa_B_III_3_A': '●●●● Kredyty i pożyczki',
    'Pasywa_B_III_3_B': '●●●● Z tytułu emisji dłużnych papierów wartościowych',
    'Pasywa_B_III_3_C': '●●●● Inne zobowiązania finansowe',
    'Pasywa_B_III_3_D': '●●●● Z tytułu dostaw i usług, o okresie wymagalności',
    'Pasywa_B_III_3_D_1': '●●●●● Do 12 miesięcy',
    'Pasywa_B_III_3_D_2': '●●●●● Powyżej 12 miesięcy',
    'Pasywa_B_III_3_E': '●●●● Zaliczki otrzymane na dostawy i usługi',
    'Pasywa_B_III_3_F': '●●●● Zobowiązania wekslowe',
    'Pasywa_B_III_3_G': '●●●● Z tytułu podatków, ceł, ubezpieczeń społecznych i zdrowotnych oraz innych tytułów publicznoprawnych',
    'Pasywa_B_III_3_H': '●●●● Z tytułu wynagrodzeń',
    'Pasywa_B_III_3_I': '●●●● Inne',
    'Pasywa_B_III_4': '●●● Fundusze specjalne',
    'Pasywa_B_IV': '●● Rozliczenia międzyokresowe',
    'Pasywa_B_IV_1': '●●● Ujemna wartość firmy',
    'Pasywa_B_IV_2': '●●● Inne rozliczenia międzyokresowe',
    'Pasywa_B_IV_2_1': '●●●● Długoterminowe', 
    'Pasywa_B_IV_2_2': '●●●● Krótkoterminowe', 
}

rzis_dict = {
    'RZiSPor': 'Wariant Porownawczy',
    'A': 'Przychody netto ze sprzedaży i zrównane z nimi, w tym:',
    'A_J': '● Od jednostek powiązanych',
    'A_I': '● Przychody netto ze sprzedaży produktów',
    'A_II': '● Zmiana stanu produktów (zwiększenie – wartość dodatnia, zmniejszenie – wartość ujemna)',
    'A_III': '● Koszt wytworzenia produktów na własne potrzeby jednostki',
    'A_IV': '● Przychody netto ze sprzedaży towarów i materiałów',
    'B': 'Koszty działalności operacyjnej',
    'B_I': '● Amortyzacja',
    'B_II': '● Zużycie materiałów i energii',
    'B_III': '● Usługi obce',
    'B_IV': '● Podatki i opłaty, w tym:', 
    'B_IV_1': '●● Podatek akcyzowy',
    'B_V': '● Wynagrodzenia', 
    'B_VI': '● Ubezpieczenia społeczne i inne świadczenia, w tym:',
    'B_VI_1': '●● Emerytalne',
    'B_VII': '● Pozostałe koszty rodzajowe',
    'B_VIII': '● Wartość sprzedanych towarów i materiałów',
    'C': 'Zysk (strata) ze sprzedaży (A–B)',
    'D': 'Pozostałe przychody operacyjne',
    'D_I': '● Zysk z tytułu rozchodu niefinansowych aktywów trwałych',
    'D_II': '● Dotacje',
    'D_III': '● Aktualizacja wartości aktywów niefinansowych',
    'D_IV': '● Inne przychody operacyjne',
    'E': 'Pozostałe koszty operacyjne',
    'E_I': '● Strata z tytułu rozchodu niefinansowych aktywów trwałych',
    'E_II': '● Aktualizacja wartości aktywów niefinansowych',
    'E_III':'● Inne koszty operacyjne',
    'F': 'Zysk (strata) z działalności operacyjnej (C+D–E)',
    'G': 'Przychody finansowe',
    'G_I': '● Dywidendy i udziały w zyskach, w tym:',
    'G_I_A': '●● Od jednostek powiązanych, w tym:',
    'G_I_A_1': '●●● W których jednostka posiada zaangażowanie w kapitale',
    'G_I_B': '●● Od jednostek pozostałych, w tym:',
    'G_I_B_1': '●●● W których jednostka posiada zaangażowanie w kapitale',
    'G_II': '● Odsetki, w tym:',
    'G_II_J': '●● Od jednostek powiązanych',
    'G_III': '● Zysk z tytułu rozchodu aktywów finansowych, w tym:',
    'G_III_J': '●● W jednostkach powiązanych',
    'G_IV': '● Aktualizacja wartości aktywów finansowych',
    'G_V': '● Inne',
    'H': 'Koszty finansowe', 
    'H_I': '● Odsetki, w tym:',
    'H_I_J': '●● Dla jednostek powiązanych',
    'H_II': '● Strata z tytułu rozchodu aktywów finansowych, w tym:',
    'H_II_J': '●● W jednostkach powiązanych',
    'H_III': '● Aktualizacja wartości aktywów finansowych',
    'H_IV': '● Inne',
    'I': 'Zysk (strata) brutto (F+G–H)', 
    'J': 'Podatek dochodowy', 
    'K': 'Pozostałe obowiązkowe zmniejszenia zysku (zwiększenia straty)',
    'L': 'Zysk (strata) netto (I–J–K)',
}

zmiany_dict = {
    'I': 'Kapitał (fundusz) własny na początek okresu (BO)',
    'I_1': '● Zmiany przyjętych zasad (polityki) rachunkowości',
    'I_2': '● Korekty błędów',
    'IA': 'Kapitał (fundusz) własny na początek okresu (BO), po korektach',
    'IA_1': '● Kapitał (fundusz) podstawowy na początek okresu',
    'IA_1_1': '●● Zmiany kapitału (funduszu) podstawowego', 
    'IA_1_1_A': '●●● Zwiększenie (z tytułu)',
    'IA_1_1_A_1': '●●●● Wydania udziałów (emisji akcji)',
    'IA_1_1_B': '●●● Zmniejszenie (z tytułu)',
    'IA_1_1_B_1': '●●●● Umorzenia udziałów (akcji)',
    'IA_1_2': '●● Kapitał (fundusz) podstawowy na koniec okresu',
    'IA_2': '● Kapitał (fundusz) zapasowy na początek okresu',
    'IA_2_1': '●● Zmiany kapitału (funduszu) zapasowego',
    'IA_2_1_A': '●●● Zwiększenie (z tytułu)',
    'IA_2_1_A_1': '●●●● Emisji akcji powyżej wartości nominalnej',
    'IA_2_1_A_2': '●●●● Podziału zysku (ustawowo)',
    'IA_2_1_A_3': '●●●● Podziału zysku (ponad wymaganą ustawowo minimalną wartość)',
    'IA_2_1_B': '●●● Zmniejszenie (z tytułu)', 
    'IA_2_1_B_1': '●●●● Pokrycia straty',
    'IA_2_2': '●● Stan kapitału (funduszu) zapasowego na koniec okresu',
    'IA_3': '● Kapitał (fundusz) z aktualizacji wyceny na początek okresu – zmiany przyjętych zasad (polityki) rachunkowości',
    'IA_3_1': '●● Zmiany kapitału (funduszu) z aktualizacji wyceny',
    'IA_3_1_A': '●●● Zwiększenie (z tytułu)',
    'IA_3_1_B': '●●● Zmniejszenie (z tytułu)',
    'IA_3_1_B_1': '●●●● Zbycia środków trwałych',
    'IA_3_2': '●● Kapitał (fundusz) z aktualizacji wyceny na koniec okresu',
    'IA_4': '● Pozostałe kapitały (fundusze) rezerwowe na początek okresu',
    'IA_4_1': '●● Zmiany pozostałych kapitałów (funduszy) rezerwowych', 
    'IA_4_1_A': '●●● Zwiększenie (z tytułu)',
    'IA_4_1_B': '●●● Zmniejszenie (z tytułu)',
    'IA_4_2': '●● Pozostałe kapitały (fundusze) rezerwowe na koniec okresu',
    'IA_5': '● Zysk (strata) z lat ubiegłych na początek okresu',
    'IA_5_1': '●● Zysk z lat ubiegłych na początek okresu',
    'IA_5_1_1': '●●● Zmiany przyjętych zasad (polityki) rachunkowości',
    'IA_5_1_2': '●●● Korekty błędów',
    'IA_5_2': '●● Zysk z lat ubiegłych na początek okresu, po korektach',
    'IA_5_2_A': '●●● Zwiększenie (z tytułu)',
    'IA_5_2_A_1': '●●●● Podziału zysku z lat ubiegłych',
    'IA_5_2_B': '●●● Zmniejszenie (z tytułu)',
    'PozycjaUszczegolawiajaca': '',
    'NazwaPozycji': '',
    'IA_5_3': '●● Zysk z lat ubiegłych na koniec okresu',
    'IA_5_4': '●● Strata z lat ubiegłych na początek okresu',
    'IA_5_4_1': '●●● Zmiany przyjętych zasad (polityki) rachunkowości',
    'IA_5_4_2': '●●● Korekty błędów',
    'IA_5_5': '●● Strata z lat ubiegłych na początek okresu, po korektach',
    'IA_5_5_A': '●●● Zwiększenie (z tytułu)',
    'IA_5_5_A_1': '●●●● Przeniesienia straty z lat ubiegłych do pokrycia',
    'IA_5_5_B': '●●● Zmniejszenie (z tytułu)',
    'IA_5_6': '●● Strata z lat ubiegłych na koniec okresu',
    'IA_5_7': '●● Zysk (strata) z lat ubiegłych na koniec okresu',
    'IA_6': '● Wynik netto',
    'IA_6_A': '●● Zysk netto',
    'IA_6_B': '●● Strata netto',
    'IA_6_C': '●● Odpisy z zysku',
    'II':'Kapitał (fundusz) własny na koniec okresu (BZ)',
    'III': 'Kapitał (fundusz) własny, po uwzględnieniu proponowanego podziału zysku (pokrycia straty)'
}

rachunek_dict = {
    'PrzeplywyPosr': 'Metoda pośrednia',
    'A': 'Przepływy środków pieniężnych z działalności operacyjnej',
    'A_I': '● Zysk (strata) netto',
    'A_II': '● Korekty razem',
    'A_II_1': '●● Amortyzacja',
    'A_II_2': '●● Zyski (straty) z tytułu różnic kursowych',
    'A_II_3': '●● Odsetki i udziały w zyskach (dywidendy)',
    'A_II_4': '●● Zysk (strata) z działalności inwestycyjnej',
    'A_II_5': '●● Zmiana stanu rezerw',
    'A_II_6': '●● Zmiana stanu zapasów',
    'A_II_7': '●● Zmiana stanu należności', 
    'A_II_8': '●● Zmiana stanu zobowiązań krótkoterminowych, z wyjątkiem pożyczek i kredytów',
    'A_II_9': '●● Zmiana stanu rozliczeń międzyokresowych',
    'A_II_10': '●● Inne korekty',
    'A_III': '● Przepływy pieniężne netto z działalności operacyjnej (I±II)',
    'B': 'Przepływy środków pieniężnych z działalności inwestycyjnej',
    'B_I': '● Wpływy',
    'B_I_1': '●● Zbycie wartości niematerialnych i prawnych oraz rzeczowych aktywów trwałych',
    'B_I_2': '●● Zbycie inwestycji w nieruchomości oraz wartości niematerialne i prawne',
    'B_I_3': '●● Z aktywów finansowych, w tym:',
    'B_I_3_A': '●●● W jednostkach powiązanych',
    'B_I_3_B': '●●● W pozostałych jednostkach',
    'B_I_3_B_1': '●●●● Zbycie aktywów finansowych',
    'B_I_3_B_2': '●●●● Dywidendy i udziały w zyskach',
    'B_I_3_B_3': '●●●● Spłata udzielonych pożyczek długoterminowych',
    'B_I_3_B_4': '●●●● Odsetki',
    'B_I_3_B_5': '●●●● Inne wpływy z aktywów finansowych',
    'B_I_4': '●● Inne wpływy inwestycyjne',
    'B_II': '● Wydatki',
    'B_II_1': '●● Nabycie wartości niematerialnych i prawnych oraz rzeczowych aktywów trwałych',
    'B_II_2': '●● Inwestycje w nieruchomości oraz wartości niematerialne i prawne',
    'B_II_3': '●● Na aktywa finansowe, w tym:',
    'B_II_3_A': '●●● W jednostkach powiązanych',
    'B_II_3_B': '●●● W pozostałych jednostkach',
    'B_II_3_B_1': '●●●● Nabycie aktywów finansowych',
    'B_II_3_B_2': '●●●● Udzielone pożyczki długoterminowe',
    'B_II_4': '●● Inne wydatki inwestycyjne',
    'B_III': '● Przepływy pieniężne netto z działalności inwestycyjnej (I–II)',
    'C': 'Przepływy środków pieniężnych z działalności finansowej',
    'C_I': '● Wpływy',
    'C_I_1': '●● Wpływy netto z wydania udziałów (emisji akcji) i innych instrumentów kapitałowych oraz dopłat do kapitału',
    'C_I_2': '●● Kredyty i pożyczki',
    'C_I_3': '●● Emisja dłużnych papierów wartościowych',
    'C_I_4': '●● Inne wpływy finansowe',
    'C_II': '● Wydatki',
    'C_II_1': '●● Nabycie udziałów (akcji) własnych',
    'C_II_2': '●● Dywidendy i inne wypłaty na rzecz właścicieli',
    'C_II_3': '●● Inne, niż wypłaty na rzecz właścicieli, wydatki z tytułu podziału zysku',
    'C_II_4': '●● Spłaty kredytów i pożyczek',
    'C_II_5': '●● Wykup dłużnych papierów wartościowych',
    'C_II_6': '●● Z tytułu innych zobowiązań finansowych',
    'C_II_7': '●● Płatności zobowiązań z tytułu umów leasingu finansowego',
    'C_II_8': '●● Odsetki',
    'C_II_9': '●● Inne wydatki finansowe',
    'C_III': '● Przepływy pieniężne netto z działalności finansowej (I–II)',
    'D': 'Przepływy pieniężne netto, razem (A.III±B.III±C.III)', 
    'E': 'Bilansowa zmiana stanu środków pieniężnych, w tym:', 
    'E_1': '● Zmiana stanu środków pieniężnych z tytułu różnic kursowych',
    'F': 'Środki pieniężne na początek okresu',
    'G': 'Środki pieniężne na koniec okresu (F±D), w tym:',
    'G_1': '● O ograniczonej możliwości dysponowania',
}